server:
  port: 8080

spring:
  profiles:
    active: prod

person:
  lastName: hello
  age: ${random.int}
  boss: false
  birth: 2022/02/14
  maps: { k1: v1,k2: v2 }
  lists:
    - lisi
    - zhouliu
  dog:
    name: 小狗
    age: 12



---
spring:
  profiles: dev

server:
  port: 8081

---
spring:
  profiles: prod

server:
  port: 8082